In [25]:
import cfbd
import pandas as pd
import json
from nltk import word_tokenize
import re
import numpy as np
from pprint import pprint
import requests
import string

In [26]:
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = 'mgcrMMYLaaITESSL77nY1ccFZXw/nYHKw7kf2cKBEK2FsxUsUCu8VKohqtbiG4qp'
configuration.api_key_prefix['Authorization'] = 'Bearer'

api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games = api_instance.get_games(year=2020, week=1)
api_instance2 = cfbd.BettingApi(cfbd.ApiClient(configuration))
api_instance3 = cfbd.TeamsApi(cfbd.ApiClient(configuration))
api_instance4 = cfbd.PlaysApi(cfbd.ApiClient(configuration))

In [27]:
games_by_year = []
lines_by_year = []
def get_years():
    
    year = [2015, 2016, 2017, 2018, 2019, 2020]
    api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
    api_instance2 = cfbd.BettingApi(cfbd.ApiClient(configuration))
    
    for i in range(len(year)):
        games_by_year.append(api_instance.get_games(year=year[i]))
        lines_by_year.append(api_instance2.get_lines(year=year[i]))
        


games_by_id = []
lines_by_id = []
def all_games():
    
    for i in range(len(games_by_year)):
        x = games_by_year[i]
        
        for j in range(len(x)):
            games_by_id.append(x[j])
    
    for i in range(len(lines_by_year)):
        y = lines_by_year[i]
        
        for j in range(len(y)):
            lines_by_id.append(y[j])

In [28]:
games_by_year

[]

In [29]:
get_years()
all_games()

In [30]:
df = pd.DataFrame()

for i in range(len(games_by_id)):
        
    games_0 = str(games_by_id[i])
    toks = re.split(r'[,]', games_0)
    
    cols = []
    data = []
    for i in range(len(toks)):
        toks2 = re.split(r'[:]', toks[i])
    
        if len(toks2) < 2:
            pass
    
        else:
            cols.append(toks2[0])
            data.append(toks2[1])
            
    
  
    data_arr = np.array(data)
    
    df2 = pd.DataFrame(data_arr.reshape(1,25), columns=cols)
        
    df = df.append(df2)

In [31]:
df.head()

,{'attendance',\n 'away_conference',\n 'away_id',\n 'away_line_scores',\n 'away_points',\n 'away_post_win_prob',\n 'away_team',\n 'conference_game',\n 'excitement_index',\n 'highlights',...,\n 'home_team',\n 'id',\n 'neutral_site',\n 'season',\n 'season_type',\n 'start_date',\n 'start_time_tbd',\n 'venue',\n 'venue_id',\n 'week'
0,51664,'ACC',153,[7,13,0.6775406749476023,'North Carolina',False,7.94978585869999,None,...,'South Carolina',400603840,True,2015,'regular','2015-09-03T22,None,'Bank of America Stadium',3628,1}
0,39184,'Conference USA',2229,[3,15,0.8986826867755855,'Florida International',False,5.3903379073,None,...,'UCF',400763593,False,2015,'regular','2015-09-03T22,None,'Bright House Networks Stadium',3652,1}
0,19717,'Big 12',197,[3,24,0.9137049802164213,'Oklahoma State',False,3.1885406359,None,...,'Central Michigan',400763399,False,2015,'regular','2015-09-03T23,None,'Kelly/Shorts Stadium',3786,1}
0,27126,None,2210,[0,3,1.3822027318810548e-05,'Elon',False,2.0872957646,None,...,'Wake Forest',400756896,False,2015,'regular','2015-09-03T23,None,'BB&T Field',3630,1}
0,10473,None,2678,[0,36,0.46662017111500487,'VMI',False,4.7380781049,None,...,'Ball State',400787299,False,2015,'regular','2015-09-03T23,None,'Scheumann Stadium',3919,1}

In [32]:
df.shape

(4730, 25)

# Betting Lines

In [41]:
lines_arr = []
for i in range(len(lines_by_id)):    
    lines_0 = str(lines_by_id[i])
    lines_toks = re.split(r'[,]', lines_0)
    lines_arr.append(lines_toks)

In [42]:
lines_arr[0]

["{'away_conference': 'Big 12'",
 "\n 'away_score': 23",
 "\n 'away_team': 'TCU'",
 "\n 'home_conference': 'Big Ten'",
 "\n 'home_score': 17",
 "\n 'home_team': 'Minnesota'",
 "\n 'id': 400763398",
 "\n 'lines': [{'awayMoneyline': None",
 "\n            'formattedSpread': 'TCU -16'",
 "\n            'homeMoneyline': None",
 "\n            'overUnder': None",
 "\n            'overUnderOpen': None",
 "\n            'provider': 'consensus'",
 "\n            'spread': '16'",
 "\n            'spreadOpen': None}",
 "\n           {'awayMoneyline': None",
 "\n            'formattedSpread': 'TCU -15.5'",
 "\n            'homeMoneyline': None",
 "\n            'overUnder': '57'",
 "\n            'overUnderOpen': None",
 "\n            'provider': 'numberfire'",
 "\n            'spread': '15.5'",
 "\n            'spreadOpen': None}",
 "\n           {'awayMoneyline': None",
 "\n            'formattedSpread': 'TCU -16.5'",
 "\n            'homeMoneyline': None",
 "\n            'overUnder': '57'",
 "\n            'overUnderOpen': None",
 "\n            'provider': 'teamrankings'",
 "\n            'spread': '16.5'",
 "\n            'spreadOpen': None}]",
 "\n 'season': 2015",
 "\n 'season_type': 'regular'",
 "\n 'week': 1}"]

In [43]:
new_lst = []

for i in range(len(lines_arr)):
    id_cnt=0
    spread_cnt1=0
    spread_cnt2=0
    
    for j in range(len(lines_arr[i])):
        id_cnt+=1
        spread_cnt1+=1
        spread_cnt2+=1
        
        if len(lines_arr[i]) < 20:
            continue
        
        if id_cnt == 7:
            new_lst.append(lines_arr[i][j])
        
        if spread_cnt1 == 9:
            new_lst.append(lines_arr[i][j])
        
        if spread_cnt2 == 20:
            new_lst.append(lines_arr[i][j])
    
new_lst

["\n 'id': 400763398",
 "\n            'formattedSpread': 'TCU -16'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756882",
 "\n            'formattedSpread': 'Arizona -30.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603840",
 "\n            'formattedSpread': 'South Carolina -3.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763593",
 "\n            'formattedSpread': 'UCF -17'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763399",
 "\n            'formattedSpread': 'Oklahoma State -20.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603839",
 "\n            'formattedSpread': 'Vanderbilt -17.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756883",
 "\n            'formattedSpread': 'Utah -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787302",
 "\n            'formattedSpread': 'Ohio -7'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756894",
 "\n            'formattedSpread': 'Duke -13.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764855",
 "\n            'formattedSpread': 'Baylor -20'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763470",
 "\n            'formattedSpread': 'Michigan State -23.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756888",
 "\n            'formattedSpread': 'Boise State -11'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763587",
 "\n            'formattedSpread': 'Georgia State -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603827",
 "\n            'formattedSpread': 'Alabama -10'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603829",
 "\n            'formattedSpread': 'Auburn -10.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756884",
 "\n            'formattedSpread': 'USC -27'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603831",
 "\n            'formattedSpread': 'Georgia -31'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756899",
 "\n            'formattedSpread': 'Florida State -37'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763403",
 "\n            'formattedSpread': 'Notre Dame -9'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756904",
 "\n            'formattedSpread': 'UCLA -14.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603838",
 "\n            'formattedSpread': 'Texas A&M -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603828",
 "\n            'formattedSpread': 'Arkansas -35'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763404",
 "\n            'formattedSpread': 'Oklahoma -38'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756891",
 "\n            'formattedSpread': 'Stanford -10'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400834350",
 "\n            'formattedSpread': 'Tennessee -17'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787107",
 '\n            \'formattedSpread\': "Hawai\'i -2.5"',
 "\n            'overUnderOpen': None",
 "\n 'id': 400835430",
 "\n            'formattedSpread': 'Illinois -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763495",
 "\n            'formattedSpread': 'Nebraska -7.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763588",
 "\n            'formattedSpread': 'Eastern Michigan -7'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763497",
 "\n            'formattedSpread': 'Penn State -14'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763592",
 "\n            'formattedSpread': 'Tulsa -21'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756901",
 "\n            'formattedSpread': 'NC State -23'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603832",
 "\n            'formattedSpread': 'Kentucky -16.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763407",
 "\n            'formattedSpread': 'West Virginia -38'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603830",
 "\n            'formattedSpread': 'Florida -38'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787115",
 "\n            'formattedSpread': 'Northern Illinois -16'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603836",
 "\n            'formattedSpread': 'Mississippi State -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763498",
 "\n            'formattedSpread': 'Purdue -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756905",
 "\n            'formattedSpread': 'Ohio State -14'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763599",
 "\n            'formattedSpread': 'Western Kentucky -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787981",
 "\n            'formattedSpread': 'Utah -11'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756912",
 "\n            'formattedSpread': 'Miami -16.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763505",
 "\n            'formattedSpread': 'Ohio State -38'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757018",
 "\n            'formattedSpread': 'Michigan State -5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757014",
 "\n            'formattedSpread': 'USC -43.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756917",
 "\n            'formattedSpread': 'Notre Dame -11.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603870",
 "\n            'formattedSpread': 'Georgia -17'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400792601",
 "\n            'formattedSpread': 'Florida State -29'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756907",
 "\n            'formattedSpread': 'Clemson -21'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757015",
 "\n            'formattedSpread': 'UCLA -28'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603865",
 "\n            'formattedSpread': 'LSU -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756910",
 "\n            'formattedSpread': 'Georgia Tech -26'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603869",
 "\n            'formattedSpread': 'Texas A&M -26'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603866",
 "\n            'formattedSpread': 'Ole Miss -23'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603861",
 "\n            'formattedSpread': 'Arkansas -21'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603868",
 "\n            'formattedSpread': 'Oklahoma -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787118",
 "\n            'formattedSpread': 'Boise State -1.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603862",
 "\n            'formattedSpread': 'Missouri -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756892",
 "\n            'formattedSpread': 'Arizona -10.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757019",
 "\n            'formattedSpread': 'Michigan -14'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400760492",
 "\n            'formattedSpread': 'Connecticut -6.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763414",
 "\n            'formattedSpread': 'Kansas State -22.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763502",
 "\n            'formattedSpread': 'Maryland -10'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756911",
 "\n            'formattedSpread': 'Louisville -12.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763506",
 "\n            'formattedSpread': 'Penn State -16.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763508",
 "\n            'formattedSpread': 'Wisconsin -33'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756916",
 "\n            'formattedSpread': 'Syracuse -5.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757016",
 "\n            'formattedSpread': 'Colorado -16'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763415",
 "\n            'formattedSpread': 'Texas Tech -16.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763499",
 "\n            'formattedSpread': 'Minnesota -5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757021",
 "\n            'formattedSpread': 'Rutgers -5.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787119",
 "\n            'formattedSpread': 'Wyoming -11'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763409",
 "\n            'formattedSpread': 'Iowa -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757022",
 "\n            'formattedSpread': 'California -9'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787308",
 "\n            'formattedSpread': 'Western Michigan -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763597",
 "\n            'formattedSpread': 'SMU -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763595",
 "\n            'formattedSpread': 'Marshall -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603864",
 "\n            'formattedSpread': 'Florida -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763410",
 "\n            'formattedSpread': 'Memphis -10.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603867",
 "\n            'formattedSpread': 'South Carolina -7.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763503",
 "\n            'formattedSpread': 'Nebraska -27'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763413",
 "\n            'formattedSpread': 'Texas -16'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763501",
 "\n            'formattedSpread': 'Indiana -7.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764862",
 "\n            'formattedSpread': 'Cincinnati -6.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764863",
 "\n            'formattedSpread': 'New Mexico -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787415",
 "\n            'formattedSpread': 'New Mexico State -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787117",
 "\n            'formattedSpread': 'Air Force -7'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757023",
 "\n            'formattedSpread': 'Stanford -16'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756919",
 "\n            'formattedSpread': 'Clemson -5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756920",
 "\n            'formattedSpread': 'Florida State -10.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787241",
 "\n            'formattedSpread': 'Arizona State -24'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763514",
 "\n            'formattedSpread': 'Ohio State -31.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603850",
 "\n            'formattedSpread': 'Alabama -8.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763420",
 "\n            'formattedSpread': 'TCU -38'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763512",
 "\n            'formattedSpread': 'Michigan State -27.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757026",
 "\n            'formattedSpread': 'USC -8'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603852",
 "\n            'formattedSpread': 'Georgia -15.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756922",
 "\n            'formattedSpread': 'Notre Dame -2'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757027",
 "\n            'formattedSpread': 'UCLA -14.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757030",
 "\n            'formattedSpread': 'Oregon -48.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603854",
 "\n            'formattedSpread': 'LSU -6.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763418",
 "\n            'formattedSpread': 'Oklahoma -33'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603858",
 "\n            'formattedSpread': 'Texas A&M -25'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757029",
 "\n            'formattedSpread': 'Utah -15.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603856",
 "\n            'formattedSpread': 'Missouri -24'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756921",
 "\n            'formattedSpread': 'Duke -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763516",
 "\n            'formattedSpread': 'Wisconsin -35'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763419",
 "\n            'formattedSpread': 'Oklahoma State -24.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763510",
 "\n            'formattedSpread': 'Maryland -7.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763511",
 "\n            'formattedSpread': 'Michigan -34'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756915",
 "\n            'formattedSpread': 'Pittsburgh -11.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756924",
 "\n            'formattedSpread': 'North Carolina -7'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756930",
 "\n            'formattedSpread': 'Wake Forest -2'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756927",
 "\n            'formattedSpread': 'Syracuse -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763605",
 "\n            'formattedSpread': 'Rice -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764869",
 "\n            'formattedSpread': 'Temple -9'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787311",
 "\n            'formattedSpread': 'Ball State -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764864",
 "\n            'formattedSpread': 'Memphis -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763417",
 "\n            'formattedSpread': 'Kansas State -11'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764865",
 "\n            'formattedSpread': 'Cincinnati -19'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764866",
 "\n            'formattedSpread': 'Navy -1.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756929",
 "\n            'formattedSpread': 'Virginia Tech -5.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756923",
 "\n            'formattedSpread': 'Miami -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763509",
 "\n            'formattedSpread': 'Indiana -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757032",
 "\n            'formattedSpread': 'Washington -3.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763603",
 "\n            'formattedSpread': 'Middle Tennessee -19.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763606",
 "\n            'formattedSpread': 'Texas State -2'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603851",
 "\n            'formattedSpread': 'Arkansas -10.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756925",
 "\n            'formattedSpread': 'NC State -15'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757028",
 "\n            'formattedSpread': 'Colorado State -1'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603853",
 "\n            'formattedSpread': 'Florida -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757034",
 "\n            'formattedSpread': 'California -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763515",
 "\n            'formattedSpread': 'Penn State -7'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763604",
 "\n            'formattedSpread': 'UTEP -4'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787243",
 "\n            'formattedSpread': 'San Diego State -15.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756926",
 "\n            'formattedSpread': 'Iowa -3'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757031",
 "\n            'formattedSpread': 'Oregon State -8'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763421",
 "\n            'formattedSpread': 'Toledo -6.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757033",
 "\n            'formattedSpread': 'Washington State -24'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764870",
 "\n            'formattedSpread': 'Memphis -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763600",
 "\n            'formattedSpread': 'Florida Atlantic -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763524",
 "\n            'formattedSpread': 'Ohio State -27'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763520",
 "\n            'formattedSpread': 'Michigan State -28.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763425",
 "\n            'formattedSpread': 'TCU -9.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603847",
 "\n            'formattedSpread': 'Ole Miss -28'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763422",
 "\n            'formattedSpread': 'Baylor -33'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763583",
 "\n            'formattedSpread': 'Notre Dame -28.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603849",
 "\n            'formattedSpread': 'LSU -24'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757036",
 "\n            'formattedSpread': 'UCLA -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603841",
 "\n            'formattedSpread': 'Alabama -39'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757039",
 "\n            'formattedSpread': 'Oregon -14'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603842",
 "\n            'formattedSpread': 'Texas A&M -3.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763523",
 "\n            'formattedSpread': 'Northwestern -18'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400757037",
 "\n            'formattedSpread': 'USC -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756933",
 "\n            'formattedSpread': 'Georgia Tech -10'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763519",
 "\n            'formattedSpread': 'Michigan -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763527",
 "\n            'formattedSpread': 'Wisconsin -28'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763424",
 "\n            'formattedSpread': 'Oklahoma State -5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603846",
 "\n            'formattedSpread': 'Kentucky -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763423",
 "\n            'formattedSpread': 'Rutgers -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763522",
 "\n            'formattedSpread': 'Nebraska -24.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603848",
 "\n            'formattedSpread': 'South Carolina -12.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400764871",
 "\n            'formattedSpread': 'Navy -8'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763526",
 "\n            'formattedSpread': 'Purdue -1.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756938",
 "\n            'formattedSpread': 'Indiana -3.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756932",
 "\n            'formattedSpread': 'Boston College -4.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763609",
 "\n            'formattedSpread': 'Louisiana Tech -14'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400787246",
 "\n            'formattedSpread': 'New Mexico -2.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763426",
 "\n            'formattedSpread': 'West Virginia -16.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763518",
 "\n            'formattedSpread': 'Iowa -26.5'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400763521",
 "\n            'formattedSpread': 'Minnesota -13'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400756937",
 "\n            'formattedSpread': 'Virginia Tech -6'",
 "\n            'overUnderOpen': None",
 "\n 'id': 400603844",

In [44]:
new_lst2 = []
    
for i in range(len(new_lst)):
        
    new_lines_0 = str(new_lst[i])
    new_toks = re.split(r'[,]', new_lines_0)
    
    for j in range(len(new_toks)):
        new_toks2 = re.split(r'[:]', new_toks[j])
    
        new_lst2.append(new_toks2[1])

new_lst2

[' 400763398',
 " 'TCU -16'",
 ' None',
 ' 400756882',
 " 'Arizona -30.5'",
 ' None',
 ' 400603840',
 " 'South Carolina -3.5'",
 ' None',
 ' 400763593',
 " 'UCF -17'",
 ' None',
 ' 400763399',
 " 'Oklahoma State -20.5'",
 ' None',
 ' 400603839',
 " 'Vanderbilt -17.5'",
 ' None',
 ' 400756883',
 " 'Utah -3'",
 ' None',
 ' 400787302',
 " 'Ohio -7'",
 ' None',
 ' 400756894',
 " 'Duke -13.5'",
 ' None',
 ' 400764855',
 " 'Baylor -20'",
 ' None',
 ' 400763470',
 " 'Michigan State -23.5'",
 ' None',
 ' 400756888',
 " 'Boise State -11'",
 ' None',
 ' 400763587',
 " 'Georgia State -4'",
 ' None',
 ' 400603827',
 " 'Alabama -10'",
 ' None',
 ' 400603829',
 " 'Auburn -10.5'",
 ' None',
 ' 400756884',
 " 'USC -27'",
 ' None',
 ' 400603831',
 " 'Georgia -31'",
 ' None',
 ' 400756899',
 " 'Florida State -37'",
 ' None',
 ' 400763403',
 " 'Notre Dame -9'",
 ' None',
 ' 400756904',
 " 'UCLA -14.5'",
 ' None',
 ' 400603838',
 " 'Texas A&M -3'",
 ' None',
 ' 400603828',
 " 'Arkansas -35'",
 ' None',
 ' 400763404',
 " 'Oklahoma -38'",
 ' None',
 ' 400756891',
 " 'Stanford -10'",
 ' None',
 ' 400834350',
 " 'Tennessee -17'",
 ' None',
 ' 400787107',
 ' "Hawai\'i -2.5"',
 ' None',
 ' 400835430',
 " 'Illinois -13'",
 ' None',
 ' 400763495',
 " 'Nebraska -7.5'",
 ' None',
 ' 400763588',
 " 'Eastern Michigan -7'",
 ' None',
 ' 400763497',
 " 'Penn State -14'",
 ' None',
 ' 400763592',
 " 'Tulsa -21'",
 ' None',
 ' 400756901',
 " 'NC State -23'",
 ' None',
 ' 400603832',
 " 'Kentucky -16.5'",
 ' None',
 ' 400763407',
 " 'West Virginia -38'",
 ' None',
 ' 400603830',
 " 'Florida -38'",
 ' None',
 ' 400787115',
 " 'Northern Illinois -16'",
 ' None',
 ' 400603836',
 " 'Mississippi State -13'",
 ' None',
 ' 400763498',
 " 'Purdue -2.5'",
 ' None',
 ' 400756905',
 " 'Ohio State -14'",
 ' None',
 ' 400763599',
 " 'Western Kentucky -3'",
 ' None',
 ' 400787981',
 " 'Utah -11'",
 ' None',
 ' 400756912',
 " 'Miami -16.5'",
 ' None',
 ' 400763505',
 " 'Ohio State -38'",
 ' None',
 ' 400757018',
 " 'Michigan State -5'",
 ' None',
 ' 400757014',
 " 'USC -43.5'",
 ' None',
 ' 400756917',
 " 'Notre Dame -11.5'",
 ' None',
 ' 400603870',
 " 'Georgia -17'",
 ' None',
 ' 400792601',
 " 'Florida State -29'",
 ' None',
 ' 400756907',
 " 'Clemson -21'",
 ' None',
 ' 400757015',
 " 'UCLA -28'",
 ' None',
 ' 400603865',
 " 'LSU -3'",
 ' None',
 ' 400756910',
 " 'Georgia Tech -26'",
 ' None',
 ' 400603869',
 " 'Texas A&M -26'",
 ' None',
 ' 400603866',
 " 'Ole Miss -23'",
 ' None',
 ' 400603861',
 " 'Arkansas -21'",
 ' None',
 ' 400603868',
 " 'Oklahoma -3'",
 ' None',
 ' 400787118',
 " 'Boise State -1.5'",
 ' None',
 ' 400603862',
 " 'Missouri -13'",
 ' None',
 ' 400756892',
 " 'Arizona -10.5'",
 ' None',
 ' 400757019',
 " 'Michigan -14'",
 ' None',
 ' 400760492',
 " 'Connecticut -6.5'",
 ' None',
 ' 400763414',
 " 'Kansas State -22.5'",
 ' None',
 ' 400763502',
 " 'Maryland -10'",
 ' None',
 ' 400756911',
 " 'Louisville -12.5'",
 ' None',
 ' 400763506',
 " 'Penn State -16.5'",
 ' None',
 ' 400763508',
 " 'Wisconsin -33'",
 ' None',
 ' 400756916',
 " 'Syracuse -5.5'",
 ' None',
 ' 400757016',
 " 'Colorado -16'",
 ' None',
 ' 400763415',
 " 'Texas Tech -16.5'",
 ' None',
 ' 400763499',
 " 'Minnesota -5'",
 ' None',
 ' 400757021',
 " 'Rutgers -5.5'",
 ' None',
 ' 400787119',
 " 'Wyoming -11'",
 ' None',
 ' 400763409',
 " 'Iowa -4'",
 ' None',
 ' 400757022',
 " 'California -9'",
 ' None',
 ' 400787308',
 " 'Western Michigan -4.5'",
 ' None',
 ' 400763597',
 " 'SMU -6'",
 ' None',
 ' 400763595',
 " 'Marshall -4'",
 ' None',
 ' 400603864',
 " 'Florida -13'",
 ' None',
 ' 400763410',
 " 'Memphis -10.5'",
 ' None',
 ' 400603867',
 " 'South Carolina -7.5'",
 ' None',
 ' 400763503',
 " 'Nebraska -27'",
 ' None',
 ' 400763413',
 " 'Texas -16'",
 ' None',
 ' 400763501',
 " 'Indiana -7.5'",
 ' None',
 ' 400764862',
 " 'Cincinnati -6.5'",
 ' None',
 ' 400764863',
 " 'New Mexico -3'",
 ' None',
 ' 400787415',
 " 'New Mexico State -4'",
 ' None',
 ' 400787117',
 " 'Air Force -7'",
 ' None',
 ' 400757023',
 " 'Stanford -16'",
 ' None',
 ' 400756919',
 " 'Clemson -5'",
 ' None',
 ' 400756920',
 " 'Florida State -10.5'",
 ' None',
 ' 400787241',
 " 'Arizona State -24'",
 ' None',
 ' 400763514',
 " 'Ohio State -31.5'",
 ' None',
 ' 400603850',
 " 'Alabama -8.5'",
 ' None',
 ' 400763420',
 " 'TCU -38'",
 ' None',
 ' 400763512',
 " 'Michigan State -27.5'",
 ' None',
 ' 400757026',
 " 'USC -8'",
 ' None',
 ' 400603852',
 " 'Georgia -15.5'",
 ' None',
 ' 400756922',
 " 'Notre Dame -2'",
 ' None',
 ' 400757027',
 " 'UCLA -14.5'",
 ' None',
 ' 400757030',
 " 'Oregon -48.5'",
 ' None',
 ' 400603854',
 " 'LSU -6.5'",
 ' None',
 ' 400763418',
 " 'Oklahoma -33'",
 ' None',
 ' 400603858',
 " 'Texas A&M -25'",
 ' None',
 ' 400757029',
 " 'Utah -15.5'",
 ' None',
 ' 400603856',
 " 'Missouri -24'",
 ' None',
 ' 400756921',
 " 'Duke -2.5'",
 ' None',
 ' 400763516',
 " 'Wisconsin -35'",
 ' None',
 ' 400763419',
 " 'Oklahoma State -24.5'",
 ' None',
 ' 400763510',
 " 'Maryland -7.5'",
 ' None',
 ' 400763511',
 " 'Michigan -34'",
 ' None',
 ' 400756915',
 " 'Pittsburgh -11.5'",
 ' None',
 ' 400756924',
 " 'North Carolina -7'",
 ' None',
 ' 400756930',
 " 'Wake Forest -2'",
 ' None',
 ' 400756927',
 " 'Syracuse -6'",
 ' None',
 ' 400763605',
 " 'Rice -6'",
 ' None',
 ' 400764869',
 " 'Temple -9'",
 ' None',
 ' 400787311',
 " 'Ball State -6'",
 ' None',
 ' 400764864',
 " 'Memphis -4'",
 ' None',
 ' 400763417',
 " 'Kansas State -11'",
 ' None',
 ' 400764865',
 " 'Cincinnati -19'",
 ' None',
 ' 400764866',
 " 'Navy -1.5'",
 ' None',
 ' 400756929',
 " 'Virginia Tech -5.5'",
 ' None',
 ' 400756923',
 " 'Miami -4.5'",
 ' None',
 ' 400763509',
 " 'Indiana -3'",
 ' None',
 ' 400757032',
 " 'Washington -3.5'",
 ' None',
 ' 400763603',
 " 'Middle Tennessee -19.5'",
 ' None',
 ' 400763606',
 " 'Texas State -2'",
 ' None',
 ' 400603851',
 " 'Arkansas -10.5'",
 ' None',
 ' 400756925',
 " 'NC State -15'",
 ' None',
 ' 400757028',
 " 'Colorado State -1'",
 ' None',
 ' 400603853',
 " 'Florida -4.5'",
 ' None',
 ' 400757034',
 " 'California -2.5'",
 ' None',
 ' 400763515',
 " 'Penn State -7'",
 ' None',
 ' 400763604',
 " 'UTEP -4'",
 ' None',
 ' 400787243',
 " 'San Diego State -15.5'",
 ' None',
 ' 400756926',
 " 'Iowa -3'",
 ' None',
 ' 400757031',
 " 'Oregon State -8'",
 ' None',
 ' 400763421',
 " 'Toledo -6.5'",
 ' None',
 ' 400757033',
 " 'Washington State -24'",
 ' None',
 ' 400764870',
 " 'Memphis -4.5'",
 ' None',
 ' 400763600',
 " 'Florida Atlantic -2.5'",
 ' None',
 ' 400763524',
 " 'Ohio State -27'",
 ' None',
 ' 400763520',
 " 'Michigan State -28.5'",
 ' None',
 ' 400763425',
 " 'TCU -9.5'",
 ' None',
 ' 400603847',
 " 'Ole Miss -28'",
 ' None',
 ' 400763422',
 " 'Baylor -33'",
 ' None',
 ' 400763583',
 " 'Notre Dame -28.5'",
 ' None',
 ' 400603849',
 " 'LSU -24'",
 ' None',
 ' 400757036',
 " 'UCLA -4.5'",
 ' None',
 ' 400603841',
 " 'Alabama -39'",
 ' None',
 ' 400757039',
 " 'Oregon -14'",
 ' None',
 ' 400603842',
 " 'Texas A&M -3.5'",
 ' None',
 ' 400763523',
 " 'Northwestern -18'",
 ' None',
 ' 400757037',
 " 'USC -6'",
 ' None',
 ' 400756933',
 " 'Georgia Tech -10'",
 ' None',
 ' 400763519',
 " 'Michigan -6'",
 ' None',
 ' 400763527',
 " 'Wisconsin -28'",
 ' None',
 ' 400763424',
 " 'Oklahoma State -5'",
 ' None',
 ' 400603846',
 " 'Kentucky -2.5'",
 ' None',
 ' 400763423',
 " 'Rutgers -13'",
 ' None',
 ' 400763522',
 " 'Nebraska -24.5'",
 ' None',
 ' 400603848',
 " 'South Carolina -12.5'",
 ' None',
 ' 400764871',
 " 'Navy -8'",
 ' None',
 ' 400763526',
 " 'Purdue -1.5'",
 ' None',
 ' 400756938',
 " 'Indiana -3.5'",
 ' None',
 ' 400756932',
 " 'Boston College -4.5'",
 ' None',
 ' 400763609',
 " 'Louisiana Tech -14'",
 ' None',
 ' 400787246',
 " 'New Mexico -2.5'",
 ' None',
 ' 400763426',
 " 'West Virginia -16.5'",
 ' None',
 ' 400763518',
 " 'Iowa -26.5'",
 ' None',
 ' 400763521',
 " 'Minnesota -13'",
 ' None',
 ' 400756937',
 " 'Virginia Tech -6'",
 ' None',
 ' 400603844',
 " 'Florida -3'",
 ' None',
 ' 400763610',
 " 'Appalachian State -7'",
 ' None',
 ' 400763525',
 " 'Penn State -12'",
 ' None',
 ' 400763608',
 " 'Marshall -11'",
 ' None',
 ' 400763613',
 " 'Western Kentucky -21.5'",
 ' None',
 ' 400787245',
 " 'Buffalo -3'",
 ' None',
 ' 400763517',
 " 'Illinois -7'",
 ' None',
 ' 400757040',
 " 'California -2'",
 ' None',
 ' 400760493',
 " 'Army -2'",
 ' None',
 ' 400763612',
 " 'Colorado State -9.5'",
 ' None',
 ' 400763607',
 " 'Florida Atlantic -9.5'",
 ' None',
 ' 400756931',
 " 'Boise State -4'",
 ' None',
 ' 400787314',
 " 'Toledo -10'",
 ' None',
 ' 400603843',
 " 'Auburn -3.5'",
 ' None',
 ' 400756936',
 " 'NC State -16.5'",
 ' None',
 ' 400764872',
 " 'Houston -16.5'",
 ' None',
 ' 400787443',
 " 'Georgia Southern -17'",
 ' None',
 ' 400787244',
 " 'San JosÃ© State -4'",
 ' None',
 ' 400764873',
 " 'Miami -5'",
 ' None',
 ' 400764875',
 " 'Memphis -10.5'",
 ' None',
 ' 400763614',
 " 'Temple -23.5'",
 ' None',
 ' 400764874',
 " 'BYU -3.5'",
 ' None',
 ' 400763529',
 " 'Ohio State -17.5'",
 ' None',
 ' 400763531',
 " 'Michigan State -24.5'",
 ' None',
 ' 400603878',
 " 'Ole Miss -6.5'",
 ' None',
 ' 400763430',
 " 'TCU -18.5'",
 ' None',
 ' 400763431',
 " 'Baylor -15.5'",
 ' None',
 ' 400756940',
 " 'Clemson -3'",
 ' None',
 ' 400757042',
 " 'UCLA -13'",
 ' None',
 ' 400603879',
 " 'Georgia -1'",
 ' None',
 ' 400603881',
 " 'LSU -45'",
 ' None',
 ' 400756941',
 " 'Florida State -18'",
 ' None',
 ' 400603885',
 " 'Texas A&M -6'",
 ' None',
 ' 400763428',
 " 'Oklahoma -7.5'",
 ' None',
 ' 400763532',
 " 'Northwestern -6.5'",
 ' None',
 ' 400757041',
 " 'Stanford -14'",
 ' None',
 ' 400763533',
 " 'Wisconsin -8'",
 ' None',
 ' 400763429',
 " 'Oklahoma State -3.5'",
 ' None',
 ' 400763530',
 " 'Michigan -12'",
 ' None',
 ' 400757044',
 " 'California -13.5'",
 ' None',
 ' 400764878',
 " 'UCF -3'",
 ' None',
 ' 400764879',
 " 'Houston -9.5'",
 ' None',
 ' 400603883',
 " 'Missouri -3.5'",
 ' None',
 ' 400756945',
 " 'Virginia Tech -4.5'",
 ' None',
 ' 400760494',
 " 'Army -7.5'",
 ' None',
 ' 400763427',
 " 'Iowa State -14.5'",
 ' None',
 ' 400756943',
 " 'NC State -5'",
 ' None',
 ' 400787316',
 " 'Ohio -4'",
 ' None',
 ' 400787317',
 " 'Toledo -9.5'",
 ' None',
 ' 400787315',
 " 'Northern Illinois -2.5'",
 ' None',
 ' 400763620',
 " 'UMass -2.5'",
 ' None',
 ' 400764876',
 " 'Navy -6'",
 ' None',
 ' 400787253',
 " 'Appalachian State -17.5'",
 ' None',
 ' 400787318',
 " 'Bowling Green -6.5'",
 ' None',
 ' 400787319',
 " 'Kent State -10.5'",
 ' None',
 ' 400763616',
 " 'Marshall -18'",
 ' None',
 ' 400787313',
 " 'Louisiana -7.5'",
 ' None',
 ' 400756942',
 " 'Georgia Tech -10.5'",
 ' None',
 ' 400603877',
 " 'Auburn -20.5'",
 ' None',
 ' 400764877',
 " 'East Carolina -6.5'",
 ' None',
 ' 400763528',
 " 'Nebraska -7.5'",
 ' None',
 ' 400763618',
 " 'Southern Mississippi -13.5'",
 ' None',
 ' 400603884',
 " 'Tennessee -7.5'",
 ' None',
 ' 400603882',
 " 'Middle Tennessee -4.5'",
 ' None',
 ' 400763615',
 " 'Louisiana Tech -14'",
 ' None',
 ' 400787251',
 " 'Nevada -11.5'",
 ' None',
 ' 400787249',
 " 'Utah State -7'",
 ' None',
 ' 400787444',
 " 'Arkansas State -20.5'",
 ' None',
 ' 400787445',
 " 'Georgia Southern -6'",
 ' None',
 ' 400763619',
 " 'UT San Antonio -2'",
 ' None',
 ' 400787252',
 " 'New Mexico -14'",
 ' None',
 ' 400787248',
 " 'Boise State -23.5'",
 ' None',
 ' 400787250',
 " 'San Diego State -9.5'",
 ' None',
 ' 400757043',
 " 'Oregon -12'",
 ' None',
 ' 400757045',
 " 'USC -17'",
 ' None',
 ' 400764880',
 " 'Houston -21'",
 ' None',
 ' 400763623',
 " 'Marshall -6.5'",
 ' None',
 ' 400756946',
 " 'Virginia Tech -2'",
 ' None',
 ' 400763537',
 " 'Ohio State -28.5'",
 ' None',
 ' 400763433',
 " 'TCU -7'",
 ' None',
 ' 400763432',
 " 'Baylor -38'",
 ' None',
 ' 400763540',
 " 'Michigan State -17'",
 ' None',
 ' 400757048',
 " 'Utah -7'",
 ' None',
 ' 400756948',
 " 'Clemson -7.5'",
 ' None',
 ' 400603903',
 " 'South Carolina -13'",
 ' None',
 ' 400603899',
 " 'Alabama -16'",
 ' None',
 ' 400763434',
 " 'Oklahoma -13.5'",
 ' None',
 ' 400603901',
 " 'Florida -3.5'",
 ' None',
 ' 400756950',
 " 'Florida State -9'",
 ' None',
 ' 400763535',
 " 'Michigan -10'",
 ' None',
 ' 400603902',
 " 'Ole Miss -43'",
 ' None',
 ' 400763584',
 " 'Notre Dame -16'",
 ' None',
 ' 400603904',
 " 'Georgia -2.5'",
 ' None',
 ' 400763436',
 " 'West Virginia -6'",
 ' None',
 ' 400763534',
 " 'Iowa -10'",
 ' None',
 ' 400787320',
 " 'Toledo -15.5'",
 ' None',
 ' 400787255',
 " 'Boise State -12'",
 ' None',
 ' 400756949',
 " 'Duke -11'",
 ' None',
 ' 400763622',
 " 'Florida International -13'",
 ' None',
 ' 400763626',
 " 'Western Kentucky -7.5'",
 ' None',
 ' 400763538',
 " 'Penn State -8'",
 ' None',
 ' 400764882',
 " 'Temple -14.5'",
 ' None',
 ' 400756939',
 " 'Duke -7'",
 ' None',
 ' 400756951',
 " 'Pittsburgh -10'",
 ' None',
 ' 400787325',
 " 'Ohio -17.5'",
 ' None',
 ' 400787321',
 " 'Bowling Green -13.5'",
 ' None',
 ' 400763621',
 " 'Florida Atlantic -1.5'",
 ' None',
 ' 400756947',
 " 'Boston College -9'",
 ' None',
 ' 400787322',
 " 'Akron -9'",
 ' None',
 ' 400787448',
 " 'Appalachian State -18'",
 ' None',
 ' 400787324',
 " 'Northern Illinois -10.5'",
 ' None',
 ' 400756952',
 " 'South Florida -5'",
 ' None',
 ' 400763536',
 " 'Nebraska -1'",
 ' None',
 ' 400763539',
 " 'Minnesota -2.5'",
 ' None',
 ' 400763435',
 " 'Texas Tech -11.5'",
 ' None',
 ' 400764884',
 " 'UCF -3'",
 ' None',
 ' 400757046',
 " 'Arizona -12.5'",
 ' None',
 ' 400603900',
 " 'Mississippi State -31.5'",
 ' None',
 ' 400757049',
 " 'Oregon -20'",
 ' None',
 ' 400764883',
 " 'Tulsa -7'",
 ' None',
 ' 400787449',
 " 'Louisiana -4'",
 ' None',
 ' 400787258',
 " 'Nevada -6'",
 ' None',
 ' 400763625',
 " 'Louisiana Tech -11.5'",
 ' None',
 ' 400764881',
 " 'BYU -8.5'",
 ' None',
 ' 400787259',
 " 'San JosÃ© State -3'",
 ' None',
 ' 400757047',
 " 'Arizona State -12.5'",
 ' None',
 ' 400787254',
 " 'Air Force -21.5'",
 ' None',
 ' 400787256',
 " 'Utah State -10'",
 ' None',
 ' 400787257',
 " 'San Diego State -2'",
 ' None',
 ' 400787450',
 " 'Arkansas State -6'",
 ' None',
 ' 400757050',
 " 'Stanford -5'",
 ' None',
 ' 400603898',
 " 'Auburn -1'",
 ' None',
 ' 400763629',
 " 'Western Kentucky -26.5'",
 ' None',
 ' 400790882',
 " 'Boise State -8.5'",
 ' None',
 ' 400764885',
 " 'Houston -16'",
 ' None',
 ' 400764886',
 " 'BYU -7'",
 ' None',
 ' 400790883',
 " 'UNLV -5.5'",
 ' None',
 ' 400763545',
 " 'Ohio State -17.5'",
 ' None',
 ' 400763437',
 " 'Baylor -18'",
 ' None',
 ' 400763438',
 " 'TCU -18'",
 ' None',
 ' 400757052',
 " 'Utah -6.5'",
 ' None',
 ' 400756953',
 " 'Clemson -15.5'",
 ' None',
 ' 400603893',
 " 'LSU -6.5'",
 ' None',
 ' 400763542',
 " 'Michigan -7'",
 ' None',
 ' 400603897',
 " 'Alabama -3'",
 ' None',
 ' 400756954',
 " 'Florida State -9'",
 ' None',
 ' 400603894',
 " 'Ole Miss -10.5'",
 ' None',
 ' 400757053',
 " 'Notre Dame -3'",
 ' None',
 ' 400763544',
 " 'Iowa -2.5'",
 ' None',
 ' 400787323',
 " 'Western Michigan -5'",
 ' None',
 ' 400787328',
 " 'Ohio -4'",
 ' None',
 ' 400764887',
 " 'Connecticut -1.5'",
 ' None',
 ' 400764888',
 " 'East Carolina -11'",
 ' None',
 ' 400763546',
 " 'Wisconsin -20.5'",
 ' None',
 ' 400763627',
 " 'Marshall -6.5'",
 ' None',
 ' 400763628',
 " 'Middle Tennessee -7'",
 ' None',
 ' 400763439',
 " 'Texas Tech -27'",
 ' None',
 ' 400603895',
 " 'Mississippi State -15.5'",
 ' None',
 ' 400756955',
 " 'Georgia Tech -3'",
 ' None',
 ' 400787332',
 " 'Central Michigan -7'",
 ' None',
 ' 400787327',
 " 'Northern Illinois -15.5'",
 ' None',
 ' 400787331',
 ...]

In [45]:
new_lst2 = np.reshape(new_lst2, (4168,3))
new_lst2

array([[' 400763398', " 'TCU -16'", ' None'],
       [' 400756882', " 'Arizona -30.5'", ' None'],
       [' 400603840', " 'South Carolina -3.5'", ' None'],
       ...,
       [' 401264085', " 'Cincinnati -14.0'", ' None'],
       [' 401237074', " 'Alabama -16.5'", ' None'],
       [' 401269378', " 'Arizona State -7.5'", ' None']], dtype='<U30')

In [46]:
columns = ['id', 'Spread1', 'Spread2']
new_df = pd.DataFrame(new_lst2, columns=columns)
new_df = new_df.drop(['Spread2'],axis=1)
new_df.head()

           id                  Spread1
0   400763398                'TCU -16'
1   400756882          'Arizona -30.5'
2   400603840    'South Carolina -3.5'
3   400763593                'UCF -17'
4   400763399   'Oklahoma State -20.5'

In [47]:
spread_arr = np.array(new_df['Spread1'])
spread_arr

array([" 'TCU -16'", " 'Arizona -30.5'", " 'South Carolina -3.5'", ...,
       " 'Cincinnati -14.0'", " 'Alabama -16.5'", " 'Arizona State -7.5'"],
      dtype=object)

In [48]:
spread_name = []
spread_num = []
remove = dict.fromkeys(map(ord, '\n' + string.punctuation.replace('.','')))
for i in range(len(spread_arr)):    
    z = str(spread_arr[i])
    w = re.split(r'[-]', z)
    spread_name.append(w[0].translate(remove))
    spread_num.append(w[1].translate(remove))

In [49]:
for i in range(len(spread_num)):
    if spread_num[i] == 'null':
        spread_num[i] = None

spread_num[148]

'4.5'

In [50]:
new_df['Spread_Favorite'] = spread_name
new_df['Spread_Amount'] = spread_num
new_df = new_df.drop(['Spread1'],axis=1)

new_df.head()

           id   Spread_Favorite Spread_Amount
0   400763398              TCU             16
1   400756882          Arizona           30.5
2   400603840   South Carolina            3.5
3   400763593              UCF             17
4   400763399   Oklahoma State           20.5

In [51]:
new_df['Spread_Amount'] = pd.to_numeric(new_df['Spread_Amount'])
new_df.head()

           id   Spread_Favorite  Spread_Amount
0   400763398              TCU            16.0
1   400756882          Arizona            30.5
2   400603840   South Carolina             3.5
3   400763593              UCF            17.0
4   400763399   Oklahoma State            20.5

In [52]:
new_df = new_df.dropna()

# Cleaning DF

In [53]:
df = df.rename(columns={df.columns[0]: 'attendance', 
                        df.columns[1]: 'away_conference', 
                        df.columns[2]: 'away_id',
                        df.columns[3]: 'away_line_scores',
                        df.columns[4]: 'away_points',
                        df.columns[5]: 'away_post_win_prob',
                        df.columns[6]: 'away_team',
                        df.columns[7]: 'conference_game',
                        df.columns[8]: 'excitement_index',
                        df.columns[9]: 'highlights',
                        df.columns[10]: 'home_conference',
                        df.columns[11]: 'home_id',
                        df.columns[12]: 'home_line_scores',
                        df.columns[13]: 'home_points',
                        df.columns[14]: 'home_post_win_prob',
                        df.columns[15]: 'home_team',
                        df.columns[16]: 'id',
                        df.columns[17]: 'neutral_site',
                        df.columns[18]: 'season',
                        df.columns[19]: 'season_type',
                        df.columns[20]: 'start_date',
                        df.columns[21]: 'start_time_tbd',
                        df.columns[22]: 'venue',
                        df.columns[23]: 'venue_id',
                        df.columns[24]: 'week'})

In [54]:
df.head()

,attendance,away_conference,away_id,away_line_scores,away_points,away_post_win_prob,away_team,conference_game,excitement_index,highlights,...,home_team,id,neutral_site,season,season_type,start_date,start_time_tbd,venue,venue_id,week
0,51664,'ACC',153,[7,13,0.6775406749476023,'North Carolina',False,7.94978585869999,None,...,'South Carolina',400603840,True,2015,'regular','2015-09-03T22,None,'Bank of America Stadium',3628,1}
0,39184,'Conference USA',2229,[3,15,0.8986826867755855,'Florida International',False,5.3903379073,None,...,'UCF',400763593,False,2015,'regular','2015-09-03T22,None,'Bright House Networks Stadium',3652,1}
0,19717,'Big 12',197,[3,24,0.9137049802164213,'Oklahoma State',False,3.1885406359,None,...,'Central Michigan',400763399,False,2015,'regular','2015-09-03T23,None,'Kelly/Shorts Stadium',3786,1}
0,27126,None,2210,[0,3,1.3822027318810548e-05,'Elon',False,2.0872957646,None,...,'Wake Forest',400756896,False,2015,'regular','2015-09-03T23,None,'BB&T Field',3630,1}
0,10473,None,2678,[0,36,0.46662017111500487,'VMI',False,4.7380781049,None,...,'Ball State',400787299,False,2015,'regular','2015-09-03T23,None,'Scheumann Stadium',3919,1}

In [55]:
df['home_team'].value_counts()

 'Alabama'             46
 'Auburn'              45
 'Tennessee'           44
 'Clemson'             44
 'Arkansas'            43
                       ..
 'Coastal Carolina'    23
 'UAB'                 22
 'Liberty'             18
 'Idaho'               17
 'Campbell'             1
Name: home_team, Length: 132, dtype: int64

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4730 entries, 0 to 0
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   attendance          4730 non-null   object
 1   away_conference     4730 non-null   object
 2   away_id             4730 non-null   object
 3   away_line_scores    4730 non-null   object
 4   away_points         4730 non-null   object
 5   away_post_win_prob  4730 non-null   object
 6   away_team           4730 non-null   object
 7   conference_game     4730 non-null   object
 8   excitement_index    4730 non-null   object
 9   highlights          4730 non-null   object
 10  home_conference     4730 non-null   object
 11  home_id             4730 non-null   object
 12  home_line_scores    4730 non-null   object
 13  home_points         4730 non-null   object
 14  home_post_win_prob  4730 non-null   object
 15  home_team           4730 non-null   object
 16  id                  4730 non-null   object
 17  neutral_site        4730 non-null   object
 18  season              4730 non-null   object
 19  season_type         4730 non-null   object
 20  start_date          4730 non-null   object
 21  start_time_tbd      4730 non-null   object
 22  venue               4730 non-null   object
 23  venue_id            4730 non-null   object
 24  week                4730 non-null   object
dtypes: object(25)
memory usage: 960.8+ KB

In [57]:
df = df.drop(['away_id',
              'away_line_scores',
              'away_post_win_prob',
              'highlights',
              'home_id',
              'home_line_scores',
              'home_post_win_prob',
              'venue_id'], axis=1)

df.head()

,attendance,away_conference,away_points,away_team,conference_game,excitement_index,home_conference,home_points,home_team,id,neutral_site,season,season_type,start_date,start_time_tbd,venue,week
0,51664,'ACC',13,'North Carolina',False,7.94978585869999,'SEC',17,'South Carolina',400603840,True,2015,'regular','2015-09-03T22,None,'Bank of America Stadium',1}
0,39184,'Conference USA',15,'Florida International',False,5.3903379073,'American Athletic',14,'UCF',400763593,False,2015,'regular','2015-09-03T22,None,'Bright House Networks Stadium',1}
0,19717,'Big 12',24,'Oklahoma State',False,3.1885406359,'Mid-American',13,'Central Michigan',400763399,False,2015,'regular','2015-09-03T23,None,'Kelly/Shorts Stadium',1}
0,27126,None,3,'Elon',False,2.0872957646,'ACC',41,'Wake Forest',400756896,False,2015,'regular','2015-09-03T23,None,'BB&T Field',1}
0,10473,None,36,'VMI',False,4.7380781049,'Mid-American',48,'Ball State',400787299,False,2015,'regular','2015-09-03T23,None,'Scheumann Stadium',1}

In [58]:
df = df.drop(['start_time_tbd'], axis=1)
df.head()

,attendance,away_conference,away_points,away_team,conference_game,excitement_index,home_conference,home_points,home_team,id,neutral_site,season,season_type,start_date,venue,week
0,51664,'ACC',13,'North Carolina',False,7.94978585869999,'SEC',17,'South Carolina',400603840,True,2015,'regular','2015-09-03T22,'Bank of America Stadium',1}
0,39184,'Conference USA',15,'Florida International',False,5.3903379073,'American Athletic',14,'UCF',400763593,False,2015,'regular','2015-09-03T22,'Bright House Networks Stadium',1}
0,19717,'Big 12',24,'Oklahoma State',False,3.1885406359,'Mid-American',13,'Central Michigan',400763399,False,2015,'regular','2015-09-03T23,'Kelly/Shorts Stadium',1}
0,27126,None,3,'Elon',False,2.0872957646,'ACC',41,'Wake Forest',400756896,False,2015,'regular','2015-09-03T23,'BB&T Field',1}
0,10473,None,36,'VMI',False,4.7380781049,'Mid-American',48,'Ball State',400787299,False,2015,'regular','2015-09-03T23,'Scheumann Stadium',1}

In [59]:
df['away_points'] = pd.to_numeric(df['away_points'])
df['home_points'] = pd.to_numeric(df['home_points'])

In [60]:
one = np.array(df['away_points'])
two = np.array(df['home_points'])

home_win = []
for i in range(len(one)):
    if two[i] > one[i]:
        home_win.append(1)
    elif two[i] < one[i]:
        home_win.append(0)
    else:
        home_win.append('tie')

In [61]:
df['home_win'] = home_win

df.head()

,attendance,away_conference,away_points,away_team,conference_game,excitement_index,home_conference,home_points,home_team,id,neutral_site,season,season_type,start_date,venue,week,home_win
0,51664,'ACC',13,'North Carolina',False,7.94978585869999,'SEC',17,'South Carolina',400603840,True,2015,'regular','2015-09-03T22,'Bank of America Stadium',1},1
0,39184,'Conference USA',15,'Florida International',False,5.3903379073,'American Athletic',14,'UCF',400763593,False,2015,'regular','2015-09-03T22,'Bright House Networks Stadium',1},0
0,19717,'Big 12',24,'Oklahoma State',False,3.1885406359,'Mid-American',13,'Central Michigan',400763399,False,2015,'regular','2015-09-03T23,'Kelly/Shorts Stadium',1},0
0,27126,None,3,'Elon',False,2.0872957646,'ACC',41,'Wake Forest',400756896,False,2015,'regular','2015-09-03T23,'BB&T Field',1},1
0,10473,None,36,'VMI',False,4.7380781049,'Mid-American',48,'Ball State',400787299,False,2015,'regular','2015-09-03T23,'Scheumann Stadium',1},1

In [62]:
df = df.drop(['away_points'],axis=1)
df = df.drop(['home_points'],axis=1)
df = df.drop(['season'],axis=1)
df = df.drop(['start_date'],axis=1)

df.head()

,attendance,away_conference,away_team,conference_game,excitement_index,home_conference,home_team,id,neutral_site,season_type,venue,week,home_win
0,51664,'ACC','North Carolina',False,7.94978585869999,'SEC','South Carolina',400603840,True,'regular','Bank of America Stadium',1},1
0,39184,'Conference USA','Florida International',False,5.3903379073,'American Athletic','UCF',400763593,False,'regular','Bright House Networks Stadium',1},0
0,19717,'Big 12','Oklahoma State',False,3.1885406359,'Mid-American','Central Michigan',400763399,False,'regular','Kelly/Shorts Stadium',1},0
0,27126,None,'Elon',False,2.0872957646,'ACC','Wake Forest',400756896,False,'regular','BB&T Field',1},1
0,10473,None,'VMI',False,4.7380781049,'Mid-American','Ball State',400787299,False,'regular','Scheumann Stadium',1},1

# Combined DF

In [63]:
comb_df = pd.merge(df,new_df,on="id")
comb_df.head()

,attendance,away_conference,away_team,conference_game,excitement_index,home_conference,home_team,id,neutral_site,season_type,venue,week,home_win,Spread_Favorite,Spread_Amount
0,51664,'ACC','North Carolina',False,7.94978585869999,'SEC','South Carolina',400603840,True,'regular','Bank of America Stadium',1},1,South Carolina,3.5
1,39184,'Conference USA','Florida International',False,5.3903379073,'American Athletic','UCF',400763593,False,'regular','Bright House Networks Stadium',1},0,UCF,17.0
2,19717,'Big 12','Oklahoma State',False,3.1885406359,'Mid-American','Central Michigan',400763399,False,'regular','Kelly/Shorts Stadium',1},0,Oklahoma State,20.5
3,30307,'Conference USA','Western Kentucky',False,5.6575509609,'SEC','Vanderbilt',400603839,False,'regular','Vanderbilt Stadium',1},0,Vanderbilt,17.5
4,47825,'Big Ten','Michigan',False,4.6176711164,'Pac-12','Utah',400756883,False,'regular','Rice-Eccles Stadium',1},1,Utah,3.0

In [64]:
comb_df = comb_df.drop(['excitement_index'],axis=1)

In [65]:
comb_df['away_conference'] = comb_df['away_conference'].str.replace('[^\w\s]','')
comb_df['home_conference'] = comb_df['home_conference'].str.replace('[^\w\s]','')
comb_df['away_team'] = comb_df['away_team'].str.replace('[^\w\s]','')
comb_df['home_team'] = comb_df['home_team'].str.replace('[^\w\s]','')
comb_df['season_type'] = comb_df['season_type'].str.replace('[^\w\s]','')
comb_df['venue'] = comb_df['venue'].str.replace('[^\w\s]','')
comb_df['week'] = comb_df['week'].str.replace('[^\w\s]','')
comb_df.head()

,attendance,away_conference,away_team,conference_game,home_conference,home_team,id,neutral_site,season_type,venue,week,home_win,Spread_Favorite,Spread_Amount
0,51664,ACC,North Carolina,False,SEC,South Carolina,400603840,True,regular,Bank of America Stadium,1,1,South Carolina,3.5
1,39184,Conference USA,Florida International,False,American Athletic,UCF,400763593,False,regular,Bright House Networks Stadium,1,0,UCF,17.0
2,19717,Big 12,Oklahoma State,False,MidAmerican,Central Michigan,400763399,False,regular,KellyShorts Stadium,1,0,Oklahoma State,20.5
3,30307,Conference USA,Western Kentucky,False,SEC,Vanderbilt,400603839,False,regular,Vanderbilt Stadium,1,0,Vanderbilt,17.5
4,47825,Big Ten,Michigan,False,Pac12,Utah,400756883,False,regular,RiceEccles Stadium,1,1,Utah,3.0

In [66]:
comb_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4160 entries, 0 to 4159
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   attendance       4160 non-null   object
 1   away_conference  4160 non-null   object
 2   away_team        4160 non-null   object
 3   conference_game  4160 non-null   object
 4   home_conference  4160 non-null   object
 5   home_team        4160 non-null   object
 6   id               4160 non-null   object
 7   neutral_site     4160 non-null   object
 8   season_type      4160 non-null   object
 9   venue            4160 non-null   object
 10  week             4160 non-null   object
 11  home_win         4160 non-null   int64
 12  Spread_Favorite  4160 non-null   object
 13  Spread_Amount    4160 non-null   float64
dtypes: float64(1), int64(1), object(12)
memory usage: 487.5+ KB

In [67]:
ids = comb_df['id']
comb_df = comb_df.drop(['id'],axis=1)

In [68]:
attendance = np.array(comb_df['attendance'])
for i in range(len(attendance)):
    if attendance[i] == ' None':
        attendance[i] = None
        
comb_df['attendance'] = attendance

In [69]:
comb_df['attendance'] = pd.to_numeric(comb_df['attendance'])
comb_df['week'] = pd.to_numeric(comb_df['week'])

In [70]:
comb_df['attendance'] = comb_df['attendance'].fillna(np.mean(comb_df['attendance']))

In [71]:
comb_df = comb_df.drop(['season_type'],axis=1)

In [72]:
comb_df = comb_df.drop(['venue'],axis=1)

In [73]:
comb_df.head()

,attendance,away_conference,away_team,conference_game,home_conference,home_team,neutral_site,week,home_win,Spread_Favorite,Spread_Amount
0,51664.0,ACC,North Carolina,False,SEC,South Carolina,True,1,1,South Carolina,3.5
1,39184.0,Conference USA,Florida International,False,American Athletic,UCF,False,1,0,UCF,17.0
2,19717.0,Big 12,Oklahoma State,False,MidAmerican,Central Michigan,False,1,0,Oklahoma State,20.5
3,30307.0,Conference USA,Western Kentucky,False,SEC,Vanderbilt,False,1,0,Vanderbilt,17.5
4,47825.0,Big Ten,Michigan,False,Pac12,Utah,False,1,1,Utah,3.0

In [74]:
at = np.array(comb_df['away_team'])
ht = np.array(comb_df['home_team'])
sf = np.array(comb_df['Spread_Favorite'])
spread_favorite = []

for i in range(len(sf)):
    sf[i] = sf[i].strip()
    at[i] = at[i].strip()
    ht[i] = ht[i].strip()
    if sf[i] == at[i]:
        spread_favorite.append("Away")
    elif sf[i] == ht[i]:
        spread_favorite.append("Home")

In [75]:
comb_df['spread_favorite'] = spread_favorite
comb_df = comb_df.drop(['Spread_Favorite'],axis=1)

In [76]:
comb_df.head()

,attendance,away_conference,away_team,conference_game,home_conference,home_team,neutral_site,week,home_win,Spread_Amount,spread_favorite
0,51664.0,ACC,North Carolina,False,SEC,South Carolina,True,1,1,3.5,Home
1,39184.0,Conference USA,Florida International,False,American Athletic,UCF,False,1,0,17.0,Home
2,19717.0,Big 12,Oklahoma State,False,MidAmerican,Central Michigan,False,1,0,20.5,Away
3,30307.0,Conference USA,Western Kentucky,False,SEC,Vanderbilt,False,1,0,17.5,Home
4,47825.0,Big Ten,Michigan,False,Pac12,Utah,False,1,1,3.0,Home

In [77]:
final_df = pd.get_dummies(comb_df)
final_df.head()

,attendance,week,home_win,Spread_Amount,away_conference_ ACC,away_conference_ American Athletic,away_conference_ Big 12,away_conference_ Big Ten,away_conference_ Conference USA,away_conference_ FBS Independents,...,home_team_ Washington State,home_team_ West Virginia,home_team_ Western Kentucky,home_team_ Western Michigan,home_team_ Wisconsin,home_team_ Wyoming,neutral_site_ False,neutral_site_ True,spread_favorite_Away,spread_favorite_Home
0,51664.0,1,1,3.5,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,39184.0,1,0,17.0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
2,19717.0,1,0,20.5,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,30307.0,1,0,17.5,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4,47825.0,1,1,3.0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1

In [78]:
attendance = final_df['attendance']
week = final_df['week']
final_df = final_df.drop(['attendance'],axis=1)
#final_df = final_df.drop(['week'],axis=1)

# Model

In [79]:
import tensorflow as tf
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [80]:
y_values = final_df['home_win']
final_df = final_df.drop(['home_win'],axis=1)

In [81]:
X_train, X_test, y_train, y_test = train_test_split(final_df, y_values, test_size=0.33, random_state=42)

In [82]:
X_train.head()

,week,Spread_Amount,away_conference_ ACC,away_conference_ American Athletic,away_conference_ Big 12,away_conference_ Big Ten,away_conference_ Conference USA,away_conference_ FBS Independents,away_conference_ MidAmerican,away_conference_ Mountain West,...,home_team_ Washington State,home_team_ West Virginia,home_team_ Western Kentucky,home_team_ Western Michigan,home_team_ Wisconsin,home_team_ Wyoming,neutral_site_ False,neutral_site_ True,spread_favorite_Away,spread_favorite_Home
22,1,14.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2498,7,12.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
2471,6,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4051,13,5.5,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
695,13,17.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

# Random Forest Model

In [83]:
rf_mod = RandomForestClassifier(n_estimators=500, max_depth=10, bootstrap=True, random_state=42)

rf_mod.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=500, random_state=42)

In [84]:
rf_cv = cross_val_score(rf_mod,X_test,y_test,cv=7)

print(np.mean(rf_cv))

0.7560121945805153

# Logistic Regression Model

In [85]:
log_mod = LogisticRegression(random_state=42,solver='liblinear',max_iter=10000)

log_mod.fit(X_train,y_train)

LogisticRegression(max_iter=10000, random_state=42, solver='liblinear')

In [86]:
log_cv = cross_val_score(log_mod,X_test,y_test,cv=10)

print(np.mean(log_cv))

0.7334073838992913

# Naive Bayes Model

In [87]:
gnb = GaussianNB()

gnb.fit(X_train,y_train)

GaussianNB()

In [88]:
gnb_cv = cross_val_score(gnb,X_test,y_test,cv=10)

print(np.mean(gnb_cv))

0.5914524489580026

# Tensorflow Model

In [93]:
final_df.shape

(4160, 305)

In [94]:
nn_mod = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(305,)),
    tf.keras.layers.Dense(200, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(2)
])

In [95]:
nn_mod.compile(optimizer='Adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [96]:
history = nn_mod.fit(X_train, y_train, epochs=10, validation_split=0.3, shuffle=True)

Epoch 1/10
61/61 [==============================] - 2s 14ms/step - loss: 0.6465 - accuracy: 0.6241 - val_loss: 0.5615 - val_accuracy: 0.7276
Epoch 2/10
61/61 [==============================] - 0s 5ms/step - loss: 0.4963 - accuracy: 0.7666 - val_loss: 0.5512 - val_accuracy: 0.7216
Epoch 3/10
61/61 [==============================] - 0s 5ms/step - loss: 0.4773 - accuracy: 0.7650 - val_loss: 0.5454 - val_accuracy: 0.7336
Epoch 4/10
61/61 [==============================] - 0s 5ms/step - loss: 0.4386 - accuracy: 0.7950 - val_loss: 0.5624 - val_accuracy: 0.7168
Epoch 5/10
61/61 [==============================] - 0s 5ms/step - loss: 0.3955 - accuracy: 0.8261 - val_loss: 0.5721 - val_accuracy: 0.6930
Epoch 6/10
61/61 [==============================] - 0s 5ms/step - loss: 0.3710 - accuracy: 0.8309 - val_loss: 0.6103 - val_accuracy: 0.7204
Epoch 7/10
61/61 [==============================] - 0s 5ms/step - loss: 0.3530 - accuracy: 0.8448 - val_loss: 0.6273 - val_accuracy: 0.6918
Epoch 8/10
61/61 [==============================] - 0s 5ms/step - loss: 0.3037 - accuracy: 0.8715 - val_loss: 0.6461 - val_accuracy: 0.6882
Epoch 9/10
61/61 [==============================] - 0s 5ms/step - loss: 0.2900 - accuracy: 0.8801 - val_loss: 0.7205 - val_accuracy: 0.6882
Epoch 10/10
61/61 [==============================] - 0s 5ms/step - loss: 0.2434 - accuracy: 0.8992 - val_loss: 0.7413 - val_accuracy: 0.6941

# AdaBoost Model

In [97]:
ada_mod = AdaBoostClassifier(n_estimators=1000, learning_rate=0.5)

ada_mod.fit(X_train,y_train)

AdaBoostClassifier(learning_rate=0.5, n_estimators=1000)

In [98]:
ada_cv = cross_val_score(ada_mod,X_test,y_test,cv=7)

print(np.mean(ada_cv))

0.697022391262524

# Linear Discriminant Model

In [99]:
lda_mod = LinearDiscriminantAnalysis()

lda_mod.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [100]:
lda_cv = cross_val_score(lda_mod,X_test,y_test,cv=7)

print(np.mean(lda_cv))

0.7014029687291886